server:
  port: 10000

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

management:
  server:
    port: 10001
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

  metrics:
    enable:
      tomcat: true

transfer:
  block-attempt-count: 10
  max-period-amount: 100000

logging:
  level:
    com.swiftpay.aop: debug

